# Generated by Django 3.1.1 on 2021-03-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210326_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='host',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
